nomer.schema.input=[{"column": 3, "type":"name"}, {"column": 5, "type": "path"}]
nomer.schema.output=[{"column": 6, "type": "matchType"}, {"column":7,"type":"externalId"},{"column": 8,"type":"name"},{"column": 9,"type":"authorship"},{"column": 10, "type":"rank"}, {"column": 11,"type": "path.family.id"}, {"column": 12, "type": "path.family.name"}, {"column": 13, "type": "path.id"}, {"column": 14, "type": "path.name"}]

