nomer.schema.input=[{"column": 18, "type":"name"}, {"column": 20, "type": "path" }]
nomer.schema.output=[{"column": 21, "type": "matchType"},{"column": 22,"type":"externalId"}, {"column": 23,"type":"name"},{"column": 24, "type":"authorship"},{"column": 25,"type": "rank"}, {"column": 26,"type": "path.family.id"}, {"column": 27, "type": "path.family.name"}, {"column": 28, "type": "path.id"}, {"column": 29, "type": "path.name"}]

