nomer.schema.input=[{"column":2,"type":"externalId"},{"column": 3,"type":"name"},{"column": 4,"type": "path.family.id"}, {"column": 5, "type": "path.family.name"}]
nomer.schema.output=[{"column":2,"type":"externalId"},{"column": 3,"type":"name"},{"column": 4,"type": "path.family.id"}, {"column": 5, "type": "path.family.name"}]
