nomer.schema.input=[{"column":7,"type":"externalId"},{"column": 8,"type":"name"},{"column": 9,"type": "path.family.id"}, {"column": 10, "type": "path.family.name"}]
nomer.schema.output=[{"column":7,"type":"externalId"},{"column": 8,"type":"name"},{"column": 9,"type": "path.family.id"}, {"column": 10, "type": "path.family.name"}]
