nomer.schema.input=[{"column": 3,"type":"name"}]
nomer.schema.output=[{"column":2,"type":"externalId"},{"column": 3,"type":"name"},{"column": 4,"type":"authorship"},{"column": 5,"type": "path.family.id"}, {"column": 6, "type": "path.family.name"}, {"column": 7, "type": "path.id"}, {"column":8, "type": "path.name"}, {"column":9, "type": "matchType"}]

