nomer.schema.input=[{"column": 12,"type":"name"}]
nomer.schema.output=[{"column":11,"type":"externalId"},{"column": 12,"type":"name"},{"column": 13, "type":"authorship"},{"column": 14,"type": "path.family.id"}, {"column": 15, "type": "path.family.name"}, {"column": 16, "type": "path.id"}, {"column": 17, "type": "path.name"}, {"column": 18, "type": "matchType" }]

